#pragma once
#include "ObjLoader.h"
#include "../math/Vec3.h"

// ---------------------------------------------------------------------------
// Primitives — Default hardcoded and procedural mesh shapes
//
// These return LoadedMesh structures suitable for World::addRenderMesh.
// ---------------------------------------------------------------------------

namespace Primitives {
    // Unit cube (±1) with per-face normals and UV seams.
    // Matches the original hardcoded kDefaultVertices/kDefaultIndices layout.
    LoadedMesh cube();

    // Rectangular box scaled by extents (x, y, z).
    // Takes a Vec3 of {halfWidth, halfHeight, halfDepth} and scales the unit cube accordingly.
    LoadedMesh rect(const math::Vec3& extents);

    // Infinite plane at y = -1, XZ-aligned, facing up (+Y normal).
    // halfExtent defines the quad boundary: ±halfExtent in X and Z.
    // Default 500×500 matches the original hardcoded plane.
    LoadedMesh plane(float halfExtent = 500.0f);

    // UV sphere parametrised by rings (latitude) and sectors (longitude).
    // rings: number of horizontal latitude rings (higher = smoother, default 16)
    // sectors: number of vertical longitude divisions (higher = smoother, default 32)
    // radius: sphere radius (default 1.0)
    LoadedMesh sphere(float radius = 1.0f, int rings = 16, int sectors = 32);

    // Icosphere: high-quality sphere generated by subdividing an icosahedron.
    // subdivisions: number of subdivision levels (higher = smoother, default 3)
    //   subdivisions=0 → 20 triangles (base icosahedron)
    //   subdivisions=1 → 80 triangles
    //   subdivisions=2 → 320 triangles
    //   subdivisions=3 → 1280 triangles (default, good visual quality)
    // radius: sphere radius (default 1.0)
    LoadedMesh icosphere(float radius = 1.0f, int subdivisions = 3);
}
