#pragma once
#include <vulkan/vulkan.h>
#include <vector>
#include <memory>
#include <string>
#include "Label.h"
#include "Background.h"
#include "TexturedBackground.h"
#include "AnimatedBackground.h"
#include "CurvedBackground.h"
#include "TextBox.h"
#include "TextAtlas.h"
#include "gpu/Texture.h"
#include "gpu/UIBuffer.h"
#include "math/Vec2.h"
#include "math/Vec4.h"

class GpuDevice;

// ---------------------------------------------------------------------------
// UIManager
//
// Owns all Label instances.  Each frame:
//   1. buildFrame() depth-sorts labels, calls buildMesh() on each visible one,
//      and appends to the provided UIBuffer.
//   2. Renderer iterates getDrawCalls() to issue draw commands.
//
// Coordinate convention: all positions are in [0,1] screen percentage,
// top-left origin, Y increasing downward.
// ---------------------------------------------------------------------------

class UIManager {
public:
    UIManager() = default;
    ~UIManager() = default;

    UIManager(const UIManager&) = delete;
    UIManager& operator=(const UIManager&) = delete;

    void init(GpuDevice& gpu, VkCommandPool commandPool,
              VkDescriptorSetLayout textureLayout, float screenW, float screenH);

    void cleanup(VkDevice device);

    // Called each frame by the Engine before drawFrame().
    void update(float dt);

    // Builds the vertex/index data for this frame into buf.
    // Must be called before the Renderer records UI draw commands.
    void buildFrame(UIBuffer& buf, float screenW, float screenH);

    // Called by Engine on window resize (newW, newH in pixels).
    void handleResize(float newW, float newH);

    // Called by Engine when LMB is pressed.
    // fx, fy are [0,1] screen percentages (converted from GLFW pixels by caller).
    void handleClick(float fx, float fy, int button, int action);

    // Returns the draw calls generated by the last buildFrame().
    const std::vector<UIDrawCall>& getDrawCalls() const { return drawCalls_; }

    // Returns a valid "empty" texture descriptor set for solid-color draws
    // (the shader ignores it in state=0, but Vulkan requires a bound set).
    VkDescriptorSet dummyDescSet() const;

    // ---------------------------------------------------------------------------
    // Label factories (UIManager owns the returned pointer)
    // ---------------------------------------------------------------------------

    Background* addBackground(math::Vec2 min, math::Vec2 max,
                              math::Vec4 color, int depth = 0);

    TexturedBackground* addTexturedBackground(math::Vec2 min, math::Vec2 max,
                                              math::Vec4 tint, Texture* tex, int depth = 0);

    AnimatedBackground* addAnimatedBackground(math::Vec2 min, math::Vec2 max,
                                              math::Vec4 tint, std::vector<Texture*> frames,
                                              float fps, int depth = 0);

    CurvedBackground* addCurvedBackground(math::Vec2 min, math::Vec2 max,
                                          math::Vec4 color, float curvature = 0.5f, int depth = 0);

    TextBox* addTextBox(Background* parent, TextAtlas* atlas, const std::string& text,
                        int depth = 0, int displayPx = 0,
                        Alignment align = Alignment::DEFAULT);

    // Add a pre-constructed label (UIManager takes ownership).
    void add(std::unique_ptr<Label> label);

    // Remove and destroy a label (safe to pass nullptr).
    void remove(Label* label);

    // Load (or retrieve cached) a TextAtlas.  fontPath is relative to YOPE_ASSETS_DIR.
    TextAtlas* loadAtlas(const std::string& fontPath, int pixelSize = 0);

    // ---------------------------------------------------------------------------
    // Layout helpers
    // ---------------------------------------------------------------------------

    // Returns a min coordinate that centers a box of (width × height) on screen.
    static math::Vec2 centerMin(float width, float height) {
        return { 0.5f - width * 0.5f, 0.5f - height * 0.5f };
    }
    static math::Vec2 centerMax(float width, float height) {
        return { 0.5f + width * 0.5f, 0.5f + height * 0.5f };
    }

    // Offset a [0,1] coordinate by delta (in [0,1] units).
    static math::Vec2 offset(math::Vec2 v, float dx, float dy) {
        return { v.x + dx, v.y + dy };
    }

    static math::Vec4 rgba(float r, float g, float b, float a = 1.0f) {
        return { r, g, b, a };
    }

private:
    GpuDevice*            gpu_           = nullptr;
    VkCommandPool         commandPool_   = VK_NULL_HANDLE;
    VkDescriptorSetLayout textureLayout_ = VK_NULL_HANDLE;

    VkDescriptorPool uiDescPool_ = VK_NULL_HANDLE;

    std::vector<std::unique_ptr<Label>>    labels_;
    std::vector<std::unique_ptr<TextAtlas>> atlases_;
    std::unique_ptr<Texture>               dummyTexture_;

    std::vector<UIDrawCall> drawCalls_;

    void createDescriptorPool(VkDevice device);
    void createDummyTexture();
};
