#!/usr/bin/env python3
"""
tools/embed_assets.py
Walks the assets directory and generates two files in the output directory:
  embedded_assets.h   — declarations + getEmbeddedAsset() lookup
  embedded_assets.cpp — byte-array definitions + lookup implementation

Usage (called by CMake, not directly):
  python3 embed_assets.py <assets_dir> <output_dir>
"""

import os
import sys


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def path_to_symbol(rel_path: str) -> str:
    """Turn a relative path like 'textures/tnail.png' into a valid C identifier."""
    return "asset_" + "".join(c if c.isalnum() else "_" for c in rel_path)


def chunks(lst: list, n: int):
    for i in range(0, len(lst), n):
        yield lst[i : i + n]


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <input_dir1> [input_dir2 ...] <output_dir>", file=sys.stderr)
        sys.exit(1)

    input_dirs = sys.argv[1:-1]
    output_dir = sys.argv[-1]
    os.makedirs(output_dir, exist_ok=True)

    # Collect all files from all input directories, sorted for deterministic output.
    entries = []  # list of (rel_path, symbol, bytes)
    for input_dir in input_dirs:
        for root, _dirs, files in os.walk(input_dir):
            for filename in sorted(files):
                full_path = os.path.join(root, filename)
                rel_path  = os.path.relpath(full_path, input_dir).replace(os.sep, "/")
                symbol    = path_to_symbol(rel_path)
                with open(full_path, "rb") as f:
                    data = f.read()
                entries.append((rel_path, symbol, data))

    # ---- Header -----------------------------------------------------------
    h_path = os.path.join(output_dir, "embedded_assets.h")
    with open(h_path, "w") as h:
        h.write("// Auto-generated by tools/embed_assets.py — do not edit.\n")
        h.write("#pragma once\n")
        h.write("#include <cstddef>\n")
        h.write("#include <cstdint>\n\n")
        h.write("struct EmbeddedAsset {\n")
        h.write("    const uint8_t* data;\n")
        h.write("    std::size_t    size;\n")
        h.write("};\n\n")
        for rel_path, symbol, data in entries:
            h.write(f"// {rel_path}\n")
            h.write(f"extern const uint8_t {symbol}[{len(data)}];\n\n")
        h.write("// Returns the asset for 'path' (relative to assets/ root),\n")
        h.write("// or {nullptr, 0} if not found.\n")
        h.write("EmbeddedAsset getEmbeddedAsset(const char* path);\n")

    # ---- Implementation ---------------------------------------------------
    cpp_path = os.path.join(output_dir, "embedded_assets.cpp")
    with open(cpp_path, "w") as cpp:
        cpp.write("// Auto-generated by tools/embed_assets.py — do not edit.\n")
        cpp.write('#include "embedded_assets.h"\n')
        cpp.write("#include <cstring>\n\n")

        for rel_path, symbol, data in entries:
            cpp.write(f"// {rel_path}\n")
            cpp.write(f"const uint8_t {symbol}[{len(data)}] = {{\n")
            hex_bytes = [f"0x{b:02x}" for b in data]
            for row in chunks(hex_bytes, 16):
                cpp.write("    " + ", ".join(row) + ",\n")
            cpp.write("};\n\n")

        cpp.write("EmbeddedAsset getEmbeddedAsset(const char* path) {\n")
        for rel_path, symbol, data in entries:
            cpp.write(f'    if (std::strcmp(path, "{rel_path}") == 0)')
            cpp.write(f' return {{ {symbol}, {len(data)} }};\n')
        cpp.write("    return { nullptr, 0 };\n")
        cpp.write("}\n")

    total_bytes = sum(len(data) for _, _, data in entries)
    dir_names = ", ".join([os.path.basename(d) for d in input_dirs])
    print(f"[embed_assets] Embedded {len(entries)} file(s) from [{dir_names}], "
          f"{total_bytes:,} bytes total -> {output_dir}")


if __name__ == "__main__":
    main()